/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "StratisCPPLightClient/model/Gas.h"

namespace stratis {
namespace api {
namespace model {

Gas::Gas() {
  m_Value = 0L;
  m_ValueIsSet = false;
}

Gas::~Gas() {}

void Gas::validate() {
  // TODO: implement validation
}

web::json::value Gas::toJson() const {

  web::json::value val = web::json::value::object();

  if (m_ValueIsSet) {
    val[utility::conversions::to_string_t(U("Value"))] =
        ModelBase::toJson(m_Value);
  }

  return val;
}

bool Gas::fromJson(const web::json::value &val) {
  bool ok = true;

  if (val.has_field(utility::conversions::to_string_t(U("Value")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("Value")));
    if (!fieldValue.is_null()) {
      int64_t refVal_setValue;
      ok &= ModelBase::fromJson(fieldValue, refVal_setValue);
      setValue(refVal_setValue);
    }
  }
  return ok;
}

void Gas::toMultipart(std::shared_ptr<MultipartFormData> multipart,
                      const utility::string_t &prefix) const {
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(U("."))) {
    namePrefix += utility::conversions::to_string_t(U("."));
  }
  if (m_ValueIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("Value")), m_Value));
  }
}

bool Gas::fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                        const utility::string_t &prefix) {
  bool ok = true;
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(U("."))) {
    namePrefix += utility::conversions::to_string_t(U("."));
  }

  if (multipart->hasContent(utility::conversions::to_string_t(U("Value")))) {
    int64_t refVal_setValue;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(utility::conversions::to_string_t(U("Value"))),
        refVal_setValue);
    setValue(refVal_setValue);
  }
  return ok;
}

int64_t Gas::getValue() const { return m_Value; }

void Gas::setValue(int64_t value) {
  m_Value = value;
  m_ValueIsSet = true;
}

bool Gas::valueIsSet() const { return m_ValueIsSet; }

void Gas::unsetValue() { m_ValueIsSet = false; }
} // namespace model
} // namespace api
} // namespace stratis
