/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ApiException.h
 *
 * This is the exception being thrown in case the api call was not successful
 */

#ifndef STRATIS_API_ApiException_H_
#define STRATIS_API_ApiException_H_

#include <cpprest/details/basic_types.h>
#include <cpprest/http_msg.h>

#include <map>
#include <memory>

namespace stratis {
namespace api {

class ApiException : public web::http::http_exception {
public:
  ApiException(int errorCode, const utility::string_t &message,
               std::shared_ptr<std::istream> content = nullptr);
  ApiException(int errorCode, const utility::string_t &message,
               std::map<utility::string_t, utility::string_t> &headers,
               std::shared_ptr<std::istream> content = nullptr);
  virtual ~ApiException();

  std::map<utility::string_t, utility::string_t> &getHeaders();
  std::shared_ptr<std::istream> getContent() const;

protected:
  std::shared_ptr<std::istream> m_Content;
  std::map<utility::string_t, utility::string_t> m_Headers;
};

} // namespace api
} // namespace stratis

#endif /* STRATIS_API_ApiBase_H_ */
