/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * IHttpBody.h
 *
 * This is the interface for contents that can be sent to a remote HTTP server.
 */

#ifndef STRATIS_API_MODEL_IHttpBody_H_
#define STRATIS_API_MODEL_IHttpBody_H_

#include <iostream>

namespace stratis {
namespace api {
namespace model {

class IHttpBody {
public:
  virtual ~IHttpBody() {}

  virtual void writeTo(std::ostream &stream) = 0;
};

} // namespace model
} // namespace api
} // namespace stratis

#endif /* STRATIS_API_MODEL_IHttpBody_H_ */
