/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "lightweightapi/model/GetBalanceResponseModel.h"

namespace stratis {
namespace api {
namespace model {

GetBalanceResponseModel::GetBalanceResponseModel()
{
    m_Balance = 0L;
    m_BalanceIsSet = false;
}

GetBalanceResponseModel::~GetBalanceResponseModel() {}

void GetBalanceResponseModel::validate()
{
    // TODO: implement validation
}

web::json::value GetBalanceResponseModel::toJson() const
{
    web::json::value val = web::json::value::object();

    if (m_BalanceIsSet) {
        val[utility::conversions::to_string_t(U("Balance"))] =
            ModelBase::toJson(m_Balance);
    }

    return val;
}

bool GetBalanceResponseModel::fromJson(const web::json::value& val)
{
    bool ok = true;

    if (val.has_field(utility::conversions::to_string_t(U("Balance")))) {
        const web::json::value& fieldValue =
            val.at(utility::conversions::to_string_t(U("Balance")));
        if (!fieldValue.is_null()) {
            int64_t refVal_setBalance;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBalance);
            setBalance(refVal_setBalance);
        }
    }
    return ok;
}

void GetBalanceResponseModel::toMultipart(
    std::shared_ptr<MultipartFormData> multipart,
    const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                     utility::conversions::to_string_t(U("."))) {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if (m_BalanceIsSet) {
        multipart->add(ModelBase::toHttpContent(
            namePrefix + utility::conversions::to_string_t(U("Balance")),
            m_Balance));
    }
}

bool GetBalanceResponseModel::fromMultiPart(
    std::shared_ptr<MultipartFormData> multipart,
    const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                     utility::conversions::to_string_t(U("."))) {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if (multipart->hasContent(utility::conversions::to_string_t(U("Balance")))) {
        int64_t refVal_setBalance;
        ok &= ModelBase::fromHttpContent(
            multipart->getContent(utility::conversions::to_string_t(U("Balance"))),
            refVal_setBalance);
        setBalance(refVal_setBalance);
    }
    return ok;
}

int64_t GetBalanceResponseModel::getBalance() const { return m_Balance; }

void GetBalanceResponseModel::setBalance(int64_t value)
{
    m_Balance = value;
    m_BalanceIsSet = true;
}

bool GetBalanceResponseModel::balanceIsSet() const { return m_BalanceIsSet; }

void GetBalanceResponseModel::unsetBalance() { m_BalanceIsSet = false; }
} // namespace model
} // namespace api
} // namespace stratis
