/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ErrorResult.h
 *
 *
 */

#ifndef STRATIS_API_MODEL_ErrorResult_H_
#define STRATIS_API_MODEL_ErrorResult_H_

#include "lightweightapi/ModelBase.h"

#include "lightweightapi/Object.h"
#include <cpprest/details/basic_types.h>
#include <vector>

namespace stratis {
namespace api {
namespace model {

/// <summary>
///
/// </summary>
class ErrorResult : public ModelBase
{
public:
    ErrorResult();
    virtual ~ErrorResult();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                       const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// ErrorResult members

    /// <summary>
    ///
    /// </summary>
    std::shared_ptr<Object> getValue() const;
    bool valueIsSet() const;
    void unsetValue();

    void setValue(const std::shared_ptr<Object>& value);

    /// <summary>
    ///
    /// </summary>
    std::vector<std::shared_ptr<Object>>& getFormatters();
    bool formattersIsSet() const;
    void unsetFormatters();

    void setFormatters(const std::vector<std::shared_ptr<Object>>& value);

    /// <summary>
    ///
    /// </summary>
    std::vector<utility::string_t>& getContentTypes();
    bool contentTypesIsSet() const;
    void unsetContentTypes();

    void setContentTypes(const std::vector<utility::string_t>& value);

    /// <summary>
    ///
    /// </summary>
    utility::string_t getDeclaredType() const;
    bool declaredTypeIsSet() const;
    void unsetDeclaredType();

    void setDeclaredType(const utility::string_t& value);

    /// <summary>
    ///
    /// </summary>
    int32_t getStatusCode() const;
    bool statusCodeIsSet() const;
    void unsetStatusCode();

    void setStatusCode(int32_t value);

protected:
    std::shared_ptr<Object> m_Value;
    bool m_ValueIsSet;
    std::vector<std::shared_ptr<Object>> m_Formatters;
    bool m_FormattersIsSet;
    std::vector<utility::string_t> m_ContentTypes;
    bool m_ContentTypesIsSet;
    utility::string_t m_DeclaredType;
    bool m_DeclaredTypeIsSet;
    int32_t m_StatusCode;
    bool m_StatusCodeIsSet;
};

} // namespace model
} // namespace api
} // namespace stratis

#endif /* STRATIS_API_MODEL_ErrorResult_H_ */
