/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OwnedNFTsModel.h
 *
 *
 */

#ifndef STRATIS_API_MODEL_OwnedNFTsModel_H_
#define STRATIS_API_MODEL_OwnedNFTsModel_H_

#include "lightweightapi/ModelBase.h"

#include <map>
#include <vector>

namespace stratis {
namespace api {
namespace model {

/// <summary>
///
/// </summary>
class OwnedNFTsModel : public ModelBase
{
public:
    OwnedNFTsModel();
    virtual ~OwnedNFTsModel();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                       const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// OwnedNFTsModel members

    /// <summary>
    ///
    /// </summary>
    std::map<utility::string_t, std::vector<int64_t>>&
    getOwnedIDsByContractAddress();
    bool ownedIDsByContractAddressIsSet() const;
    void unsetOwnedIDsByContractAddress();

    void setOwnedIDsByContractAddress(
        const std::map<utility::string_t, std::vector<int64_t>>& value);

protected:
    std::map<utility::string_t, std::vector<int64_t>> m_OwnedIDsByContractAddress;
    bool m_OwnedIDsByContractAddressIsSet;
};

} // namespace model
} // namespace api
} // namespace stratis

#endif /* STRATIS_API_MODEL_OwnedNFTsModel_H_ */
