/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SendTransactionRequest.h
 *
 *
 */

#ifndef STRATIS_API_MODEL_SendTransactionRequest_H_
#define STRATIS_API_MODEL_SendTransactionRequest_H_

#include "lightweightapi/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace stratis {
namespace api {
namespace model {

/// <summary>
///
/// </summary>
class SendTransactionRequest : public ModelBase
{
public:
    SendTransactionRequest();
    virtual ~SendTransactionRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                       const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SendTransactionRequest members

    /// <summary>
    ///
    /// </summary>
    utility::string_t getHex() const;
    bool hexIsSet() const;
    void unsetHex();

    void setHex(const utility::string_t& value);

protected:
    utility::string_t m_Hex;
    bool m_HexIsSet;
};

} // namespace model
} // namespace api
} // namespace stratis

#endif /* STRATIS_API_MODEL_SendTransactionRequest_H_ */
