/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ValidatedAddress.h
 *
 *
 */

#ifndef STRATIS_API_MODEL_ValidatedAddress_H_
#define STRATIS_API_MODEL_ValidatedAddress_H_

#include "lightweightapi/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace stratis {
namespace api {
namespace model {

/// <summary>
///
/// </summary>
class ValidatedAddress : public ModelBase
{
public:
    ValidatedAddress();
    virtual ~ValidatedAddress();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                       const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// ValidatedAddress members

    /// <summary>
    ///
    /// </summary>
    bool isIsvalid() const;
    bool isvalidIsSet() const;
    void unsetIsvalid();

    void setIsvalid(bool value);

    /// <summary>
    ///
    /// </summary>
    utility::string_t getAddress() const;
    bool addressIsSet() const;
    void unsetAddress();

    void setAddress(const utility::string_t& value);

    /// <summary>
    ///
    /// </summary>
    utility::string_t getScriptPubKey() const;
    bool scriptPubKeyIsSet() const;
    void unsetScriptPubKey();

    void setScriptPubKey(const utility::string_t& value);

    /// <summary>
    ///
    /// </summary>
    bool isIsscript() const;
    bool isscriptIsSet() const;
    void unsetIsscript();

    void setIsscript(bool value);

    /// <summary>
    ///
    /// </summary>
    bool isIswitness() const;
    bool iswitnessIsSet() const;
    void unsetIswitness();

    void setIswitness(bool value);

protected:
    bool m_Isvalid;
    bool m_IsvalidIsSet;
    utility::string_t m_Address;
    bool m_AddressIsSet;
    utility::string_t m_ScriptPubKey;
    bool m_ScriptPubKeyIsSet;
    bool m_Isscript;
    bool m_IsscriptIsSet;
    bool m_Iswitness;
    bool m_IswitnessIsSet;
};

} // namespace model
} // namespace api
} // namespace stratis

#endif /* STRATIS_API_MODEL_ValidatedAddress_H_ */
