/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Money.h
 *
 *
 */

#ifndef STRATIS_API_MODEL_Money_H_
#define STRATIS_API_MODEL_Money_H_

#include "StratisCPPLightClient/ModelBase.h"

namespace stratis {
namespace api {
namespace model {

/// <summary>
///
/// </summary>
class Money : public ModelBase {
public:
  Money();
  virtual ~Money();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  bool fromJson(const web::json::value &json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t &namePrefix) const override;
  bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t &namePrefix) override;

  /////////////////////////////////////////////
  /// Money members

  /// <summary>
  ///
  /// </summary>
  int64_t getSatoshi() const;
  bool satoshiIsSet() const;
  void unsetSatoshi();

  void setSatoshi(int64_t value);

protected:
  int64_t m_Satoshi;
  bool m_SatoshiIsSet;
};

} // namespace model
} // namespace api
} // namespace stratis

#endif /* STRATIS_API_MODEL_Money_H_ */
