/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TipModel.h
 *
 *
 */

#ifndef STRATIS_API_MODEL_TipModel_H_
#define STRATIS_API_MODEL_TipModel_H_

#include "StratisCPPLightClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace stratis {
namespace api {
namespace model {

/// <summary>
///
/// </summary>
class TipModel : public ModelBase {
public:
  TipModel();
  virtual ~TipModel();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  bool fromJson(const web::json::value &json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t &namePrefix) const override;
  bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t &namePrefix) override;

  /////////////////////////////////////////////
  /// TipModel members

  /// <summary>
  ///
  /// </summary>
  utility::string_t getTipHash() const;
  bool tipHashIsSet() const;
  void unsetTipHash();

  void setTipHash(const utility::string_t &value);

  /// <summary>
  ///
  /// </summary>
  int32_t getTipHeight() const;
  bool tipHeightIsSet() const;
  void unsetTipHeight();

  void setTipHeight(int32_t value);

protected:
  utility::string_t m_TipHash;
  bool m_TipHashIsSet;
  int32_t m_TipHeight;
  bool m_TipHeightIsSet;
};

} // namespace model
} // namespace api
} // namespace stratis

#endif /* STRATIS_API_MODEL_TipModel_H_ */
