/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TransactionOutputModel.h
 *
 *
 */

#ifndef STRATIS_API_MODEL_TransactionOutputModel_H_
#define STRATIS_API_MODEL_TransactionOutputModel_H_

#include "StratisCPPLightClient/ModelBase.h"

#include "StratisCPPLightClient/model/Money.h"
#include <cpprest/details/basic_types.h>

namespace stratis {
namespace api {
namespace model {

class Money;

/// <summary>
///
/// </summary>
class TransactionOutputModel : public ModelBase {
public:
  TransactionOutputModel();
  virtual ~TransactionOutputModel();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  bool fromJson(const web::json::value &json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t &namePrefix) const override;
  bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t &namePrefix) override;

  /////////////////////////////////////////////
  /// TransactionOutputModel members

  /// <summary>
  ///
  /// </summary>
  utility::string_t getAddress() const;
  bool addressIsSet() const;
  void unsetAddress();

  void setAddress(const utility::string_t &value);

  /// <summary>
  ///
  /// </summary>
  std::shared_ptr<Money> getAmount() const;
  bool amountIsSet() const;
  void unsetAmount();

  void setAmount(const std::shared_ptr<Money> &value);

  /// <summary>
  ///
  /// </summary>
  utility::string_t getOpReturnData() const;
  bool opReturnDataIsSet() const;
  void unsetOpReturnData();

  void setOpReturnData(const utility::string_t &value);

protected:
  utility::string_t m_Address;
  bool m_AddressIsSet;
  std::shared_ptr<Money> m_Amount;
  bool m_AmountIsSet;
  utility::string_t m_OpReturnData;
  bool m_OpReturnDataIsSet;
};

} // namespace model
} // namespace api
} // namespace stratis

#endif /* STRATIS_API_MODEL_TransactionOutputModel_H_ */
