/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * WalletSendTransactionModel.h
 *
 *
 */

#ifndef STRATIS_API_MODEL_WalletSendTransactionModel_H_
#define STRATIS_API_MODEL_WalletSendTransactionModel_H_

#include "StratisCPPLightClient/ModelBase.h"

#include "StratisCPPLightClient/model/TransactionOutputModel.h"
#include <cpprest/details/basic_types.h>
#include <vector>

namespace stratis {
namespace api {
namespace model {

class TransactionOutputModel;

/// <summary>
///
/// </summary>
class WalletSendTransactionModel : public ModelBase {
public:
  WalletSendTransactionModel();
  virtual ~WalletSendTransactionModel();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  bool fromJson(const web::json::value &json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t &namePrefix) const override;
  bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t &namePrefix) override;

  /////////////////////////////////////////////
  /// WalletSendTransactionModel members

  /// <summary>
  ///
  /// </summary>
  utility::string_t getTransactionId() const;
  bool transactionIdIsSet() const;
  void unsetTransactionId();

  void setTransactionId(const utility::string_t &value);

  /// <summary>
  ///
  /// </summary>
  std::vector<std::shared_ptr<TransactionOutputModel>> &getOutputs();
  bool outputsIsSet() const;
  void unsetOutputs();

  void
  setOutputs(const std::vector<std::shared_ptr<TransactionOutputModel>> &value);

protected:
  utility::string_t m_TransactionId;
  bool m_TransactionIdIsSet;
  std::vector<std::shared_ptr<TransactionOutputModel>> m_Outputs;
  bool m_OutputsIsSet;
};

} // namespace model
} // namespace api
} // namespace stratis

#endif /* STRATIS_API_MODEL_WalletSendTransactionModel_H_ */
