/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "lightweightapi/JsonBody.h"

namespace stratis {
namespace api {
namespace model {

JsonBody::JsonBody(const web::json::value& json) : m_Json(json) {}

JsonBody::~JsonBody() {}

void JsonBody::writeTo(std::ostream& target) { m_Json.serialize(target); }

} // namespace model
} // namespace api
} // namespace stratis
